geertmeersman/telenet

.github/PULL_REQUEST_TEMPLATE.md
.github/release-drafter.yml

fix: Release drafter & PR template

---

.github/release-drafter.yml
.github/workflows/add-badges.yml
.github/workflows/version.yml
custom_components/telenet/manifest.json

fix: Workflows pushed to main

---

.github/release-drafter.yml
.github/workflows/release.yaml
custom_components/telenet/manifest.json

Release version
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

fix: Release version

---

custom_components/telenet/config_flow.py
custom_components/telenet/const.py
custom_components/telenet/sensor.py
custom_components/telenet/utils.py

- Product info sensor added
- AssertionError log improvement
Getting better & better ;-)

fix: Product info sensor and AssertionError improvement

---

.github/workflows/bandit.yml

feat: Create bandit.yml

---

.github/workflows/dependency-review.yml

feat: Create dependency-review.yml

---

custom_components/telenet/client.py

Bugfix for address fetch
- [ x I have updated the documentation accordingly.

fix: address id none

---

custom_components/telenet/entity.py

Entity id aligned with sensor name

fix: Entity id aligned with sensor name

---

.github/workflows/codeql.yml
custom_components/telenet/entity.py

fix: import format_entity_name

---

custom_components/telenet/client.py

fix: sensor name without entity id 

---

custom_components/telenet/client.py

Renamed sensor.telenet_internet_internet_usage to sensor.telenet_internet_usage

fix: Renamed sensor.telenet_internet_internet_usage to sensor.telenet_internet_usage

---

.github/workflows/pr-checker.yml
.ruff.toml
custom_components/telenet/client.py

Catching OCAPI errors in case a user doesn't have access to some functions

Catch Telenet ocapi errors

---

custom_components/telenet/entity.py

Coordinator async_update function defined

Fix update with override

---

README.md

Readme addition for dual gauge

---

README.md

Update README.md - Discord server added

---

README.md

Discord link set to never expire

Discord link set to never expire

---

.github/labels.yml
custom_components/telenet/config_flow.py

Fix error message in config flow

Fix error message in config flow

---

custom_components/telenet/config_flow.py

Indentation correction

---

.github/PULL_REQUEST_TEMPLATE.md
.github/labels.yml
README.md

Doc update

---

.pre-commit-config.yaml
custom_components/telenet/client.py

Workaround 500 bug daily usage, fixes #112

---

custom_components/telenet/__init__.py

Catch product error, fixes #120

---

README.md
custom_components/telenet/client.py

Raise TelenetServiceException when no products are found

---

README.md

Merged into HACS :-)

---

README.md

Merged into HACS Default :-)

---

README.md
custom_components/telenet/client.py

Thank you for this plugin! Just discovered it :)
This PR fixes a small spelling mistake

chore: fix spelling

---

custom_components/telenet/config_flow.py
custom_components/telenet/translations/en.json
custom_components/telenet/translations/nl.json

Config flow:  Remove email validator & language choice improvement

---

README.md

Lovelace markdown example fix

---

custom_components/telenet/client.py

Include usage sensors when no modem is available,references #139

---

custom_components/telenet/client.py

Adapt daily usage for CAP Internet category

---

custom_components/telenet/client.py

Mobile only / No children fix, fixes #140

---

custom_components/telenet/client.py
custom_components/telenet/entity.py

Correcting Telenet lastUpdate, adding timezone +0200, references #147

---

custom_components/telenet/__init__.py
custom_components/telenet/client.py
custom_components/telenet/config_flow.py
custom_components/telenet/const.py
custom_components/telenet/entity.py
custom_components/telenet/models.py
custom_components/telenet/sensor.py
custom_components/telenet/utils.py

New sensors: customer, mailboxes, simdetails, modem advanced info

---

.github/workflows/bump_version_and_release.yml
custom_components/telenet/const.py

Decrease connection timeout to 3 seconds

---

custom_components/telenet/client.py
custom_components/telenet/const.py
custom_components/telenet/models.py

Ignore advanced modem settings if no access, fixes #153

---

custom_components/telenet/client.py

Fix API endpoint

---

README.md
custom_components/telenet/client.py

V1 API: DTV & invoices

---

custom_components/telenet/client.py

V1 API: Off peak usage & total usage added

---

custom_components/telenet/client.py

V1 API: Total usage included offpeak usage

---

custom_components/telenet/utils.py

str_to_float function fix

---

custom_components/telenet/client.py

Ignore Error 500

---

custom_components/telenet/client.py

Fix if product.product_subscription_info is None

---

custom_components/telenet/client.py

fix: Restore offpeak usage

---

.github/labels.yml
.github/scripts/get_new_version.py
.github/scripts/pr_extract_labels.py
.github/workflows/pr-checker.yml
.pre-commit-config.yaml
.ruff.toml
custom_components/telenet/__init__.py
custom_components/telenet/client.py

fix: Improved debug

---

.ruff.toml
custom_components/telenet/client.py

fix: pass HTTP 500 responses for product usage

---

custom_components/telenet/client.py

fix: Bypass billcycles on 500 for specific products

---

README.md

docs: improved lovelace example for network clients

---

custom_components/telenet/client.py

I'm using the V1 API, and only one of my modems was added in Home Assistant. This PR adds all modems in the account.

V1 API: Fix multiple modems

---

.github/release-drafter-beta.yml
.github/scripts/get_new_version.py
.github/workflows/bump_version_and_prerelease.yml
custom_components/telenet/client.py

fix: throw Telenet service exception when http > 404 during login

---

custom_components/telenet/client.py

fix: create_extra_attributes_list
